Task 70
dulasevich/RestAPI pull request #7
Opened 2022-12-14 09:14 UTC by dulasevich

2022-12-21 15:31 UTC, LikBez123 requested changes

2022-12-21 15:31 UTC, LikBez123 commented on src/main/java/by/issoft/client/Client.java
> +    public static HttpResponse doPostFile(String endpoint, File file, String fileName){
what if just overload doPost method?

```
public static HttpResponse  doPost(String endpoint, File file, String fileName) {
   // same code
}
```
the idea is that rest allows us to use several methods and do different things using header, parameters, body, etc. The same approach applies to our Client. Same methods, but different abilities

2022-12-21 15:31 UTC, LikBez123 commented on src/test/java/usersTests/UploadUserTest.java
> +        userClient.createAvailableUser(new User(RandomUtils.nextInt(0, 120),
is it necessary to create new user here?

2022-12-22 09:56 UTC, dulasevich commented on src/test/java/usersTests/UploadUserTest.java
> +        userClient.createAvailableUser(new User(RandomUtils.nextInt(0, 120),
Seems like no, I removed the code.

2022-12-22 10:09 UTC, LikBez123 approved these changes

2022-12-22 10:33 UTC, merged